### ISSUE TITLE
Navigation icons causes confusion 

### ISSUE THREAD

**Issue by fatton139** [SummerProgram2018/RevYou#3]

**Comment by Chrischar** [comment]
I don't think we need to worry about this too much, The person who complained about this didn't realise tabs appear when you hover over the icons.

**Comment by Andrea9678** [comment]
dab chris

**Comment by fatton139** [comment]
Debating whether to keep the partial transparent text visible at all times or only when navigation is toggled 🤔🤔🤔🤔
